### PR TITLE
added setuptools installer 

### PR DESCRIPTION
**Pull request by oz123**
This makes installing as easy as:

python3 setup.py install 

it also sets the way for an easy installation for uploading for Pypi.python.org

### CODE REVIEW

**Comment by telmich** [comment]
Sorry for taking so long - merging!

**Comment by telmich** [comment]
Oh..cannot merge actually - can you update it to the current version?

**Comment by oz123** [comment]
Hi,
No problem. Give me a couple of days.

**Comment by oz123** [comment]
So basically you already merged the most important stuff : setup.py, and the current branch installs with it (your master). Did you cherry pick?

**Comment by telmich** [comment]
That's a really good question - if I remembered, I would tell you...

**Comment by oz123** [comment]
Any way the installer works. And my commits are there ... So I am closing the PR.

**Pull request closed without merging**
